from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from reportlab.lib import colors
import os

def generate_payslip(employee_data, output_path):
    """
    Generate a simple payslip PDF.
    employee_data: dict with keys: employee_id, name, basic_salary, allowances,
                   gross, tax, pension_employee, pension_employer, net, bank_or_telebirr
    output_path: full path where PDF will be saved.
    """
    # Ensure directory exists
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    
    # Margin
    margin = 20 * mm
    y = height - margin
    
    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, "የቀደም ፍላጎት አትፋጅ ፋትስልፒ (Payslip)")
    y -= 12
    
    # Employee info
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, f"ሰዕባ ቁ: {employee_data.get('employee_id', 'N/A')}")
    y -= 12
    c.drawString(margin, y, f"ሰው ስም: {employee_data.get('name', 'N/A')}")
    y -= 12
    c.drawString(margin, y, f"ቤተሰብ / ስልክ: {employee_data.get('bank_or_telebirr', 'N/A')}")
    y -= 20
    
    # Table header
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "የተመረጠ")
    c.drawString(margin + 60*mm, y, "የነጠረ መጠን (ETB)")
    y -= 8
    c.line(margin, y, width - margin, y)
    y -= 8
    
    # Rows
    c.setFont("Helvetica", 10)
    rows = [
        ("መሰረታዊ ደመወዝ", employee_data.get('basic_salary', 0)),
        ("አገልግሎት", employee_data.get('allowances', 0)),
        ("ገብረ ሽያጭ", employee_data.get('gross', 0)),
        ("የብልጥግና አብምር (PAYE)", employee_data.get('tax', 0)),
        ("የሰራተኛ ጡረታ (7%)", employee_data.get('pension_employee', 0)),
        ("የሰጠቀም ጡረታ (11%)", employee_data.get('pension_employer', 0)),
        ("አጠቃላይ", employee_data.get('net', 0))
    ]
    for label, value in rows:
        c.drawString(margin, y, label)
        c.drawRightString(width - margin, y, f"{value:,.2f}")
        y -= 10
    
    y -= 10
    c.line(margin, y, width - margin, y)
    y -= 12
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, f"መጠን ያገኛል: {employee_data.get('net', 0):,.2f} ETB")
    
    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(margin, margin/2, "Generated by Ethiopian Payroll Engine © 2026")
    
    c.showPage()
    c.save()
    return output_path